### ISSUE TITLE
Adding custom MAC address to docker container.

### ISSUE THREAD

**Issue by erdkse** [pierre-emmanuelJ/iptv-proxy#100]
Hey, could you please create an environment value to set desired mac address to running eth0 of the docker interface?

My Go knowledge is not enough to do that otherwise I would send a PR.

**Comment by pierre-emmanuelJ** [comment]
Hi,

You can run your container with the flag `--mac-address` and assign the MAC address you want.

See the docker-compose doc to use in there.
