### ISSUE TITLE
Panic Error Returned

### ISSUE THREAD

**Issue by c0d3r1977** [pierre-emmanuelJ/iptv-proxy#109]
This error had disspeared but its now returned. I hvae verified all settings, added and removed xstream and there error persists. 
Please advise!

2022/02/05 17:02:33 [Recovery] 2022/02/05 - 17:02:33 panic recovered:
runtime error: invalid memory address or nil pointer dereference
/opt/hostedtoolcache/go/1.17.1/x64/src/runtime/panic.go:221 (0x42dff)
/opt/hostedtoolcache/go/1.17.1/x64/src/runtime/signal_unix.go:735 (0x5d45b)
/home/runner/work/iptv-proxy/iptv-proxy/vendor/github.com/tellytv/go.xtream-codes/xtream-codes.go:82 (0x444424)
/home/runner/work/iptv-proxy/iptv-proxy/pkg/xtream-proxy/xtream-proxy.go:52 (0x4443cc)
/home/runner/work/iptv-proxy/iptv-proxy/pkg/server/xtreamHandles.go:163 (0x44aaeb)
/home/runner/work/iptv-proxy/iptv-proxy/pkg/server/xtreamHandles.go:138 (0x44a7db)
/home/runner/work/iptv-proxy/iptv-proxy/vendor/github.com/gin-gonic/gin/context.go:165 (0x42f3ab)
/home/runner/work/iptv-proxy/iptv-proxy/vendor/github.com/gin-gonic/gin/recovery.go:99 (0x42f388)
/home/runner/work/iptv-proxy/iptv-proxy/vendor/github.com/gin-gonic/gin/context.go:165 (0x42e677)
/home/runner/work/iptv-proxy/iptv-proxy/vendor/github.com/gin-gonic/gin/logger.go:241 (0x42e63c)
/home/runner/work/iptv-proxy/iptv-proxy/vendor/github.com/gin-gonic/gin/context.go:165 (0x42db9b)
/home/runner/work/iptv-proxy/iptv-proxy/vendor/github.com/gin-gonic/gin/gin.go:489 (0x42d858)
/home/runner/work/iptv-proxy/iptv-proxy/vendor/github.com/gin-gonic/gin/gin.go:445 (0x42d457)
/opt/hostedtoolcache/go/1.17.1/x64/src/net/http/server.go:2878 (0x2765fb)
/opt/hostedtoolcache/go/1.17.1/x64/src/net/http/server.go:1929 (0x271ef3)
/opt/hostedtoolcache/go/1.17.1/x64/src/runtime/asm_arm64.s:1133 (0x77963)

[GIN] 2022/02/05 - 17:02:33 | 500 |  2.145752652s |     192.168.2.2 | GET      "/player_api.php?password=xxxxxx&username=xxxxx"

**Comment by pierre-emmanuelJ** [comment]
No more Panic at this line, 😄  My fix in the go.xtream-codes package has been merged:
https://github.com/tellytv/go.xtream-codes/pull/9

This commit fixing it:
https://github.com/pierre-emmanuelJ/iptv-proxy/commit/b187b44b3b7f1f7598269ae2952cf4e461d5d78b

Try the new release:
https://github.com/pierre-emmanuelJ/iptv-proxy/releases/tag/v3.6.3
