### ISSUE TITLE
No auth option possible?

### ISSUE THREAD

**Issue by milesbarry** [pierre-emmanuelJ/iptv-proxy#11]
Hi, firstly many thanks for creating this software. I had it up and running in minutes. I have a couple of issues though.

VLC nor my AppleTV 4K IPTV player doesn't seem to like the username and password being on the end of the .ts ... I only see URL's in VLC, and can't see the actual channel name.

Would you be able to enable auth only on accessing the iptv.m3u file and not the actual streams? And / or optionally disable auth entirely , as I have a static IP at home and can put an iptables rule on the DigitalOcean server I'm using as the proxy. 

Very best wishes

**Comment by pierre-emmanuelJ** [comment]
Thank you for your issue :) weird normally don't make problems in VLC, I'm using it to.
I can add an option with no auth ASAP this week, good idea.

Thanks 🚀

**Comment by milesbarry** [comment]
> Thank you for your issue :) weird normally don't make problems in VLC, I'm using it to.
> I can add an option with no auth ASAP this week, good idea.
> 
> Thanks 🚀

That's great ! It's strange because using the proxied M3U file on VLC I see the title being the URL ... I compared both M3U files (original and proxied) and only could notice the difference being that the proxied URL has the two parameters added for username and password.

Do you have any ideas please as to why this might be happening? 

FYI providers URL looks like:

http://xxxx.xx:80/get.php?username=smart123&password=p455&type=m3u&output=ts

Best wishes

**Comment by pierre-emmanuelJ** [comment]
Oh so your provider is an xtream api provider so your should user the xtream proxy of `iptv-proxy`:
https://github.com/pierre-emmanuelJ/iptv-proxy#xtream-code-server-api-example
set up with your credential:
base url: http://xxxx.xx:80
username: smart123
password: p455

and then install this app on your apple TV:
https://apps.apple.com/fr/app/iptv-smarters-player/id1383614816

and use the xtream proxified credentials

**Comment by milesbarry** [comment]
Opps 

[GIN-debug] Listening and serving HTTP on :8080
fatal error: runtime: out of memory 

then large dump

**Comment by pierre-emmanuelJ** [comment]
Can you provide the dump? it's after using xtream service ?

**Comment by milesbarry** [comment]
Just tried your new package - sadly still fails. Not sure if it's safe posting dump here? I don't see any URL's etc in it. If not safe how can I send it to you please?

**Comment by pierre-emmanuelJ** [comment]
Send me by email if you want ;) after it's only a dump from Golang runtime so normally it's safe

**Comment by milesbarry** [comment]
Hey, sent you the dump... cheers

**Comment by pierre-emmanuelJ** [comment]
hey I make a new release with --m3u-url optional.
So use only xtrem proxy service to try thanks.

and also you will can be able to access your playlist with the xtream link.
Example:
http://proxy.com:80/get.php?username=test123&password=testproxy&type=m3u&output=ts
or use xtream credentials in app

**Comment by pierre-emmanuelJ** [comment]
okay thanks for the email ! I found the problem it's come from the get.php cache playlist!

okay for the moment use xtream proxyfied credentials as I said in the apple app
https://apps.apple.com/fr/app/iptv-smarters-player/id1383614816

and dont use proxyfied get.php url

I'll fill the cache asap

thanks for reporting

**Comment by milesbarry** [comment]
Morning. So I tried the xtreme method... It takes nearly a minute from doing the http request until getting the m3u file. VLC shows the channels correctly. However when I click on any channel they all 404.

**Comment by pierre-emmanuelJ** [comment]
first request It's long after it's cached and request take less than 1 second
for the 404 can you send me the logs

**Comment by pierre-emmanuelJ** [comment]
I close the issue because this is not the issue problem question
