### ISSUE TITLE
can someone help me installing it

### ISSUE THREAD

**Issue by djeghri** [pierre-emmanuelJ/iptv-proxy#112]
hi,
can someone please explain to me step by step installing it.
i couldn't do it by my self thanks

**Comment by pierre-emmanuelJ** [comment]
Issue section is not a forum/tutorial place...
Documentation is enough detailed, if you need help on sysadmin stuff you should ask help installing it on Reddit or forums...etc
Thanks

**Comment by djeghri** [comment]
Okay,  sorry
