### ISSUE TITLE
Cache m3u playlist (more than 15000 tracks) directly in a file to prevent  "Runtime:out of memory" on little machine < 1GB ram

### ISSUE THREAD

**Issue by pierre-emmanuelJ** [pierre-emmanuelJ/iptv-proxy#12]
the actual issue is if there is too much channels when it's parse (get the file and unmarshall),
all is unmarshalled in struct so in memory.

idea is to read and convert line by line and write directly (unmarshall in a file)

try to do the same at endpoint creation

**Comment by andersonrfsilva** [comment]
i'm getting out of memory sometimes in my machine > 1Gb.

thx you fix it! :-)
