### ISSUE TITLE
Passthrough authentication rather than pre-configured - for supporting multiple playlists

### ISSUE THREAD

**Issue by johnwigley** [pierre-emmanuelJ/iptv-proxy#122]
This is working great, but is there any chance it could have an option where it passes through the provided user/pass from the client instead of being pre-configured please?  This would allow use with multiple independent playlists/xc accounts without having to have a unique instance running per playlist.

Thanks very much.

**Comment by pierre-emmanuelJ** [comment]
Hello, thanks for your issue.
This is in the TODO issue already, thanks 
https://github.com/pierre-emmanuelJ/iptv-proxy/issues/72
support this issue to forward the topic in a higher priority
