### ISSUE TITLE
Roku ministra

### ISSUE THREAD

**Issue by simaof94** [pierre-emmanuelJ/iptv-proxy#13]
Hello, ministra player only supports .m3u8 format.. is there a way to make the output of the m3u file into m3u8? I imported m3u8 but the output does not match :/

**Comment by pierre-emmanuelJ** [comment]
Hello thanks for your issue 👍

**Comment by pierre-emmanuelJ** [comment]
https://github.com/pierre-emmanuelJ/iptv-proxy/issues/14

**Comment by pierre-emmanuelJ** [comment]
Hello, I have fixed HLS for Xtream api provier in this commit d85ffb6764f6e93405d35be1a67603d0b1a0db24.

Are you an Xtream provider? what is the format of the link are you using to access the playlist?

**Comment by simaof94** [comment]
No, I don't use Xtream, the format is hls.

**Comment by pierre-emmanuelJ** [comment]
Okay so I'll see to fix that for the playlist URL service. Thanks

**Comment by pierre-emmanuelJ** [comment]
Closing issue, duplicate: https://github.com/pierre-emmanuelJ/iptv-proxy/issues/14
being implemented.
