### ISSUE TITLE
Pls Help

### ISSUE THREAD

**Issue by Lip90** [pierre-emmanuelJ/iptv-proxy#141]
Can someone help me to install the Proxy. I tried the installation many Times with no succuss. Pls i need a stepp by stepp manual

**Comment by demarey-baker** [comment]
Are you using docker?

**Comment by Lip90** [comment]
Yes
________________________________
Von: Demarey Baker ***@***.***>
Gesendet: Saturday, February 18, 2023 12:17:41 PM
An: pierre-emmanuelJ/iptv-proxy ***@***.***>
Cc: Philipp Stiastny-Pöhlmann ***@***.***>; Author ***@***.***>
Betreff: Re: [pierre-emmanuelJ/iptv-proxy] Pls Help (Issue #141)


Are you using docker?

**Comment by demarey-baker** [comment]
Here is my docker compose file. I build a docker image from this so you can use mine. The part about macvlan is to ensure that this container gets a separate ip address from the docker host. I am assuming this is the reason you need a make it a proxy. Make sure you setup the macvlan network in docker first. You can get it to work without that by commenting out networks portion and have it use default docker bridge network or use the network_mode host mode. Let me know if you have any more issues.

version: "3"
services:
  iptv-proxy:
    image: silvadon/iptv-proxy
    container_name: iptv-proxy
    environment:
     - PORT=8080
     - HOSTNAME=<ip address>
     - GIN_MODE=release
     - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
     - XTREAM_USER=<USERNAME>
     - XTREAM_PASSWORD=<PASSWORD>
     - XTREAM_BASE_URL=<BASE_URL>
     - USER=test
     - PASSWORD=test
     #- M3U_URL: http://example.com:1234/get.php?username=user&password=pass&type=m3u_plus&output=m3u8
    ports:
      - 8080:8080
#network_mode: host    
networks:
      macvlan:
        ipv4_address: <desired-ip-address>
    restart: unless-stopped
    
networks:
  macvlan:
    external : true

**Comment by Lip90** [comment]
Many thx! The container is up and die List is loading but in die Logs i always see the error `write: broken pipe
`. Whats that?

**Comment by demarey-baker** [comment]
Never seen that error before. Might be something specific to your file.

**Comment by Lip90** [comment]
The error comes from the XTREAM EPG. Whenever the client tries to download the EPG, the "Broken Pipe Error" comes up. Do you happen to have an idea?

`[GIN] 2023/02/19 - 20:49:01 | 200 |  3.973162141s |   192.168.1.109 | GET      "/xmltv.php?username=test&password=test"`

**Comment by pierre-emmanuelJ** [comment]
You can continue to discuss in this none issue for now.
Please next time use an external Chanel like forum to discuss this kind of question, Thanks a lot :)
