### ISSUE TITLE
Error building new URL

### ISSUE THREAD

**Issue by zjuanma** [pierre-emmanuelJ/iptv-proxy#15]
I have this URL in the m3u input list:
`
http://host:port/%2525/A3E30D26A158FBE135C6BD7D65AB1B1F%252F10.ts`

and  it's build this wrong URL in the new m3u list:
`
http://localhost:80/%25/A3E30D26A158FBE135C6BD7D65AB1B1F%2F10.ts`

**Comment by pierre-emmanuelJ** [comment]
Thanks for the report I'll fix it ASAP.
I think it's come from the fact I do not escape the url char query before building the new file.
