### ISSUE TITLE
Issues with Docker for Windows?

### ISSUE THREAD

**Issue by speedyrules** [pierre-emmanuelJ/iptv-proxy#152]
Hi im running Docker under Windows (Docker Desktop) and have pulled your image through the image search in Docker Desktop.

Now i am trying the "prerequisite".. but having issues with"docker-compose up -d": the yml is being validated returns the following though: "(root) additional property environment is not allowed"

Can you help me?

**Comment by speedyrules** [comment]
this is my latest edit of the yml file
` ports:
       # have to be the same as ENV variable PORT
       - 8080:8080
 environment:
      # if you are using m3u remote file
      # M3U_URL: http://example.com:1234/get.php?username=user&password=pass&type=m3u_plus&output=m3u8
      M3U_URL: https://iptv-org.github.io/iptv/index.m3u
      # M3U_URL: /root/iptv/iptv.m3u
      # Port to expose the IPTVs endpoints
      PORT: 8080
      # Hostname or IP to expose the IPTVs endpoints (for machine not for docker)
      HOSTNAME: localhost
      GIN_MODE: release
      ## Xtream-code proxy configuration
      ## (put these env variables if you want to add xtream proxy)
      # XTREAM_USER: xtream_user
      # XTREAM_PASSWORD: xtream_password
      # XTREAM_BASE_URL: "http://example.com:1234"
      # USER: test
      # PASSWORD: testpassword`

**Comment by speedyrules** [comment]
this is the latest edit of my yml file: 

 ports:
       # have to be the same as ENV variable PORT
       - 8080:8080
 environment:
      # if you are using m3u remote file
      # M3U_URL: http://example.com:1234/get.php?username=user&password=pass&type=m3u_plus&output=m3u8
      M3U_URL: https://iptv-org.github.io/iptv/index.m3u
      # M3U_URL: /root/iptv/iptv.m3u
      # Port to expose the IPTVs endpoints
      PORT: 8080
      # Hostname or IP to expose the IPTVs endpoints (for machine not for docker)
      HOSTNAME: localhost
      GIN_MODE: release
      ## Xtream-code proxy configuration
      ## (put these env variables if you want to add xtream proxy)
      # XTREAM_USER: xtream_user
      # XTREAM_PASSWORD: xtream_password
      # XTREAM_BASE_URL: "http://example.com:1234"
      # USER: test
      # PASSWORD: testpassword

**Comment by bezalel-7** [comment]
version: "3"
services:
  iptv-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./iptv:/root/iptv
    container_name: iptv-proxy
    restart: on-failure
    ports:
      - 8080:8080
    environment:
      M3U_URL: /root/iptv/iptv.m3u
      PORT: 8080
      HOSTNAME: localhost
      GIN_MODE: release
      XTREAM_USER: xtream_user
      XTREAM_PASSWORD: xtream_password
      XTREAM_BASE_URL: "http://example.tv:8080"
      USER: test
      PASSWORD: testpassword
try this !!!!

**Comment by speedyrules** [comment]
hey @bezalel-7! Thank you for the post!

sadly it did not work.

So i replaced the M3URL .. and run several times up -d .. and everytime i # stuff.. endet uf with this returns

PS C:\docker\iptvproxy> docker-compose up -d
validating C:\docker\iptvproxy\docker-compose.yml: services must be a mapping
PS C:\docker\iptvproxy> docker-compose up -d
validating C:\docker\iptvproxy\docker-compose.yml: volumes must be a mapping
PS C:\docker\iptvproxy> docker-compose up -d
validating C:\docker\iptvproxy\docker-compose.yml: volumes must be a mapping
PS C:\docker\iptvproxy> docker-compose up -d
validating C:\docker\iptvproxy\docker-compose.yml: (root) Additional property GIN_MODE is not allowed
PS C:\docker\iptvproxy> docker-compose up -d
validating C:\docker\iptvproxy\docker-compose.yml: (root) Additional property dockerfile is not allowed
PS C:\docker\iptvproxy> docker-compose up -d
validating C:\docker\iptvproxy\docker-compose.yml: (root) Additional property USER is not allowed
PS C:\docker\iptvproxy> docker-compose up -d
validating C:\docker\iptvproxy\docker-compose.yml: (root) Additional property iptv-proxy is not allowed
PS C:\docker\iptvproxy> docker-compose up -d
validating C:\docker\iptvproxy\docker-compose.yml: (root) Additional property PORT is not allowed
PS C:\docker\iptvproxy> docker-compose up -d
validating C:\docker\iptvproxy\docker-compose.yml: (root) Additional property M3U_URL is not allowed
PS C:\docker\iptvproxy> docker-compose up -d
validating C:\docker\iptvproxy\docker-compose.yml: (root) Additional property restart is not allowed
PS C:\docker\iptvproxy> docker-compose up -d
validating C:\docker\iptvproxy\docker-compose.yml: (root) Additional property HOSTNAME is not allowed
PS C:\docker\iptvproxy> docker-compose up -d
validating C:\docker\iptvproxy\docker-compose.yml: (root) Additional property context is not allowed
PS C:\docker\iptvproxy> docker-compose up -d
validating C:\docker\iptvproxy\docker-compose.yml: (root) Additional property build is not allowed
PS C:\docker\iptvproxy> docker-compose up -d
validating C:\docker\iptvproxy\docker-compose.yml: (root) Additional property container_name is not allowed
PS C:\docker\iptvproxy> docker-compose up -d
validating C:\docker\iptvproxy\docker-compose.yml: (root) Additional property container_name is not allowed
PS C:\docker\iptvproxy> docker-compose up -d
validating C:\docker\iptvproxy\docker-compose.yml: (root) Additional property environment is not allowed
PS C:\docker\iptvproxy> docker-compose up -d
validating C:\docker\iptvproxy\docker-compose.yml: (root) Additional property ports is not allowed
PS C:\docker\iptvproxy> docker-compose up -d
validating C:\docker\iptvproxy\docker-compose.yml: (root) Additional property ports is not allowed
PS C:\docker\iptvproxy> docker-compose up -d
no service selected

and my file looked like that
version: "3"
#services:
#iptv-proxy:
#build:
#context: .
#dockerfile: Dockerfile
#volumes:
#- ./iptv:/root/iptv
#container_name: iptv-proxy
#restart: on-failure
#ports:
#- 8080:8080
#environment:
#M3U_URL: https://iptv-org.github.io/iptv/index.m3u
#PORT: 8080
#HOSTNAME: localhost
#GIN_MODE: release
#XTREAM_USER: xtream_user
#XTREAM_PASSWORD: xtream_password
#XTREAM_BASE_URL: "http://example.tv:8080"
#USER: test
#PASSWORD: testpassword

any other ideas?

**Comment by bezalel-7** [comment]
can  you check the version by running docker-compose version in the command prompt !

**Comment by speedyrules** [comment]
> can you check the version by running docker-compose version in the command prompt !

PS C:\docker\iptvproxy> docker-compose version
Docker Compose version v2.18.1

Then the Docker Engine: v24.0.2

here we go :)
