### ISSUE TITLE
Adds configurable url path to new endpoints.

### ISSUE THREAD

**Issue by zjuanma** [pierre-emmanuelJ/iptv-proxy#20]
I'm using traefik as a reverse proxy.
I have a domain and I have multiple services. If I can configure a url path for new endpoints I can using this same domain for all my services.

**Comment by pierre-emmanuelJ** [comment]
Thanks! I'll Add the feature ASAP

**Comment by pierre-emmanuelJ** [comment]
Implemented in this pr #26 
see the pr for more info in the description ;)
