### ISSUE TITLE
Configuration help

### ISSUE THREAD

**Issue by ualeci** [pierre-emmanuelJ/iptv-proxy#22]
Hi, I'm from Brazil, and I'm having trouble configuring, I don't understand the setup process very well, I'm using XtreamUI. If you have a tutorial explaining how to set up, thank you very much!

**Comment by pierre-emmanuelJ** [comment]
Hello :)

So if you are using xtreamUI your provider is an xtream one?

Please understand this xtream proxy is for the client API part.

If you have xtream client credentials and you want to proxyfie it and your don't understand how to setup it. Maybe I can make Doc tutorial or a runbook. A bit more detailed from the Readme

**Comment by ualeci** [comment]
Hello. :) Yes I am using XtreamUI, my clients are very buffered in the channels, and the solution can solve with proxy! Do you have any tutorials or videos teaching how to install iptv-proxy on the xtream Main Server.

**Comment by pierre-emmanuelJ** [comment]
So you mean a tutorial for you or your clients?

**Comment by ualeci** [comment]
for me.

 install on xtream server

**Comment by ualeci** [comment]
You have telegram or Whatsapp?

**Comment by pierre-emmanuelJ** [comment]
I'll post a little documentation ASAP 😉

**Comment by zebiden** [comment]
hi Pierre thank you for your hard work and sharing this interesting tool .well you post or pm the way to setup client proxy using XtreamUI  i appreciated your help
