### ISSUE TITLE
Compilation problem

### ISSUE THREAD

**Issue by Denzwell** [pierre-emmanuelJ/iptv-proxy#23]
Bonjour Pierre,

J'essai de mettre en oeuvre votre Reverse proxy on iptv sur une Debian 9 mais j'ai des problèmes de compilation dûe au fichier xml.
Pouvez-vous m'apporter votre aide.
Bien Cordialement

Translated issue:
> Hello Pierre,
> 
> I am trying to implement your Reverse proxy on iptv on a Debian 9 but I have problems of compilation 
due to the xml file.
> Can you help me?
> Best regards

**Comment by pierre-emmanuelJ** [comment]
Bonjour Denzwell 😀 

Please understand to post your issue in english and not in french, to help other people. Thanks.


> Hello Pierre,
> 
> I am trying to implement your Reverse proxy on iptv on a Debian 9 but I have problems of compilation > due to the xml file.
> Can you help me?
> Best regards

Can you please, give me more context? what is this xml file? how you compile...etc?

Thank you

**Comment by pierre-emmanuelJ** [comment]
Close due to an inactivity
