### ISSUE TITLE
get.php endpoint issue

### ISSUE THREAD

**Issue by smeyer73** [pierre-emmanuelJ/iptv-proxy#25]
bonjour, je n'arrive pas à faire marcher...
je lance avec:
iptv-proxy --port 8080 --hostname serveur --xtream-user aaaaaaa --xtream-password bbbbbbbbb --xtream-base-url http://blabla.blala.net:8888 --user test --password test

j'arrive à récupérer l epg avec:
http://serveur:8080/xmltv.php?username=test&password=test

mais pas le fichier playlist.... là ça il se passe rien..
ça indique juste ça:
[iptv-proxy] 2019/11/25 - 01:40:55 | 192.168.178.230 | xtream cache m3u file

voici la ligne de commande sur le client..:
http://serveur:8080/get.php?username=test&password=test&type=m3u_plus&output=ts

**Comment by pierre-emmanuelJ** [comment]
Bonjour @smeyer73  😀

Please understand to post your issue in english and not in french, to help other people. Thanks.
And please can you give an explicite title.

Translated issue:

>hello, Not working ...
>I run with:
>iptv-proxy --port 8080 --hostname server --xtream-user aaaaaaa --xtream -password bbbbbbbbb --xtream-base-url http://blabla.blala.net:8888 --user test --password test

>I can recover the epg with:
>http://server:8080/xmltv.php?username=test&password=test

>but not the playlist file .... there is nothing happening ..
>it just says that:
>[iptv-proxy] 2019/11/25 - 01:40:55 | 192.168.178.230 | xtream cache m3u file

>here is the command line on the client ..:
>http://server:8080/get.php?username=test&password=test&type=m3u_plus&output=ts


If you have an xtream provider with a lot of channels this query can take more than 40 seconds (>15 000 channels). Because it's convert all original link.

That's why I made I cache:
```
[iptv-proxy] 2019/11/25 - 01:40:55 | 192.168.178.230 | xtream cache m3u file
```

you can configure a cache expiration (default at 24h)
```
--m3u-cache-expiration int   M3U cache expiration in hour (default 24)
```

**Comment by smeyer73** [comment]
Hi, sorry for the french writing.
So I ll try now... basicly my comands are right ? and I just need to wait...

**Comment by smeyer73** [comment]
got it.


[GIN] 2019/11/25 - 19:57:47 | 200 | 1h20m17.40597044s | 192.168.178.230 | GET      /get.php?username=test&password=test&type=m3u_plus&output=ts

1000x thank you, great great program ;)

**Comment by pierre-emmanuelJ** [comment]
Omg 1h20m17s!!!! How many channels you have?
You should use an iOS/Android tv app instead of a link 😉  it’s will be faster.

Thanks

**Comment by smeyer73** [comment]
LOTS....
but only interested in the first XXXX rows
So is there a way to get the m3u file with a row limit ??? for eg adding a parameter like --MaxRow=2000
??? if possible this would speed up the process (for me)

**Comment by pierre-emmanuelJ** [comment]
Yes I understand, I can investigate that. maybe in query param xtream support that kind of operation.
example: `/get.php?username=test&password=test&type=m3u_plus&output=ts&limit=2000`
something like that.
hard to find because xtream have not official documentation.

**Comment by smeyer73** [comment]
yes, would be a very nice feature...
why not just implement a row counter when your program is grabbing/building the m3u file ?
and when the counter reaches the LIMIT parameter, just stop grabbing ?

**Comment by pierre-emmanuelJ** [comment]
Yes why not 😉 I'll see that.
Thanks


if you want to script or add a cron to cache your query every day:
```
wget https://iptv.test.xyz/iptv.m3u\?username\=xxxx\&password\=xxxx
wget https://iptv.test.xyz/get.php\?username\=xxx\&password\=xxx\&type\=m3u_plus\&output\=ts
rm iptv.m3u\?username=xxxxx\&password=xxx
rm get.php\?username=xxxxx\&password=xxx\&type=m3u_plus\&output=ts
```

**Comment by smeyer73** [comment]
thanks, i know for the scripts..

for your readers:
to lauch all;
iptv-proxy --port 8080 --hostname serveur --xtream-user XXXXXX --xtream-password AAAAAA --xtream-base-url http://DDDDDDDDDD:8000 --user test --password test &

and for plex integration
/home/oxynaz/Desktop/SCRIPTS/xteve &



to get EPG
url="http://serveur:8080/get.php?username=test&password=test&type=m3u_plus&output=ts"
echo "getting data"
wget "$url" --read-timeout=9200 -O /home/oxynaz/tmp/tmp.m3u
(timeout value is important for large m3u files)


and I would like to recommend a nice piece of software: xteve (search it on google), with this it s easy to integrate all in PLEX

**Comment by smeyer73** [comment]
and please let me know if you found a way to limit the m3u file number of rows... 
because of about 10000 rows only need the range between 0 and 2000, this range covers all my needs. So process time ll be a lot faster.

**Comment by smeyer73** [comment]
got 1 success and 1 failure..
here is the error msg for the failure:


2019/11/27 00:17:20 [Recovery] 2019/11/27 - 00:17:20 panic recovered:
GET /get.php?username=test&password=test&type=m3u_plus&output=ts HTTP/1.1
Host: serveur:8080
Accept: */*
Accept-Encoding: identity
Connection: Keep-Alive
User-Agent: Wget/1.19.4 (linux-gnu)


write tcp 127.0.1.1:8080->127.0.0.1:42910: write: broken pipe
/home/ubuntu/go/src/github.com/pierre-emmanuelJ/iptv-proxy/vendor/github.com/gin-gonic/gin/context.go:714 (0x9aaf9b)
/home/ubuntu/go/src/github.com/pierre-emmanuelJ/iptv-proxy/vendor/github.com/gin-gonic/gin/context.go:792 (0x9cc3db)
/home/ubuntu/go/src/github.com/pierre-emmanuelJ/iptv-proxy/pkg/routes/xtream.go:133 (0x9cc352)
/home/ubuntu/go/src/github.com/pierre-emmanuelJ/iptv-proxy/vendor/github.com/gin-gonic/gin/context.go:108 (0x9a7b13)
/home/ubuntu/go/src/github.com/pierre-emmanuelJ/iptv-proxy/vendor/github.com/gin-gonic/gin/recovery.go:48 (0x9b8f93)
/home/ubuntu/go/src/github.com/pierre-emmanuelJ/iptv-proxy/vendor/github.com/gin-gonic/gin/context.go:108 (0x9a7b13)
/home/ubuntu/go/src/github.com/pierre-emmanuelJ/iptv-proxy/vendor/github.com/gin-gonic/gin/logger.go:84 (0x9b834e)
/home/ubuntu/go/src/github.com/pierre-emmanuelJ/iptv-proxy/vendor/github.com/gin-gonic/gin/context.go:108 (0x9a7b13)
/home/ubuntu/go/src/github.com/pierre-emmanuelJ/iptv-proxy/vendor/github.com/gin-gonic/gin/gin.go:361 (0x9b0566)
/home/ubuntu/go/src/github.com/pierre-emmanuelJ/iptv-proxy/vendor/github.com/gin-gonic/gin/gin.go:326 (0x9afda3)
/usr/local/go/src/net/http/server.go:2802 (0x6d2a43)
/usr/local/go/src/net/http/server.go:1890 (0x6ce2e4)
/usr/local/go/src/runtime/asm_amd64.s:1357 (0x45a4c0)

[GIN-debug] [WARNING] Headers were already written. Wanted to override status code 200 with 500
[GIN] 2019/11/27 - 00:17:20 | 500 | 1h37m5.951644266s |       127.0.0.1 | GET      /get.php?username=test&password=test&type=m3u_plus&output=ts

**Comment by pierre-emmanuelJ** [comment]
> thanks, i know for the scripts..
> 
> for your readers:
> to lauch all;
> iptv-proxy --port 8080 --hostname serveur --xtream-user XXXXXX --xtream-password AAAAAA --xtream-base-url http://DDDDDDDDDD:8000 --user test --password test &
> 
> and for plex integration
> /home/oxynaz/Desktop/SCRIPTS/xteve &
> 
> to get EPG
> url="http://serveur:8080/get.php?username=test&password=test&type=m3u_plus&output=ts"
> echo "getting data"
> wget "$url" --read-timeout=9200 -O /home/oxynaz/tmp/tmp.m3u
> (timeout value is important for large m3u files)
> 
> and I would like to recommend a nice piece of software: xteve (search it on google), with this it s easy to integrate all in PLEX

Yes thanks I'm already using xteve for plex 😉 It's nice.

You have telly also but I prefer xteve like you :D

**Comment by pierre-emmanuelJ** [comment]
> got 1 success and 1 failure..
> here is the error msg for the failure:
> 
> 2019/11/27 00:17:20 [Recovery] 2019/11/27 - 00:17:20 panic recovered:
> GET /get.php?username=test&password=test&type=m3u_plus&output=ts HTTP/1.1
> Host: serveur:8080
> Accept: _/_
> Accept-Encoding: identity
> Connection: Keep-Alive
> User-Agent: Wget/1.19.4 (linux-gnu)
> 
> write tcp 127.0.1.1:8080->127.0.0.1:42910: write: broken pipe
> /home/ubuntu/go/src/github.com/pierre-emmanuelJ/iptv-proxy/vendor/github.com/gin-gonic/gin/context.go:714 (0x9aaf9b)
> /home/ubuntu/go/src/github.com/pierre-emmanuelJ/iptv-proxy/vendor/github.com/gin-gonic/gin/context.go:792 (0x9cc3db)
> /home/ubuntu/go/src/github.com/pierre-emmanuelJ/iptv-proxy/pkg/routes/xtream.go:133 (0x9cc352)
> /home/ubuntu/go/src/github.com/pierre-emmanuelJ/iptv-proxy/vendor/github.com/gin-gonic/gin/context.go:108 (0x9a7b13)
> /home/ubuntu/go/src/github.com/pierre-emmanuelJ/iptv-proxy/vendor/github.com/gin-gonic/gin/recovery.go:48 (0x9b8f93)
> /home/ubuntu/go/src/github.com/pierre-emmanuelJ/iptv-proxy/vendor/github.com/gin-gonic/gin/context.go:108 (0x9a7b13)
> /home/ubuntu/go/src/github.com/pierre-emmanuelJ/iptv-proxy/vendor/github.com/gin-gonic/gin/logger.go:84 (0x9b834e)
> /home/ubuntu/go/src/github.com/pierre-emmanuelJ/iptv-proxy/vendor/github.com/gin-gonic/gin/context.go:108 (0x9a7b13)
> /home/ubuntu/go/src/github.com/pierre-emmanuelJ/iptv-proxy/vendor/github.com/gin-gonic/gin/gin.go:361 (0x9b0566)
> /home/ubuntu/go/src/github.com/pierre-emmanuelJ/iptv-proxy/vendor/github.com/gin-gonic/gin/gin.go:326 (0x9afda3)
> /usr/local/go/src/net/http/server.go:2802 (0x6d2a43)
> /usr/local/go/src/net/http/server.go:1890 (0x6ce2e4)
> /usr/local/go/src/runtime/asm_amd64.s:1357 (0x45a4c0)
> 
> [GIN-debug] [WARNING] Headers were already written. Wanted to override status code 200 with 500
> [GIN] 2019/11/27 - 00:17:20 | 500 | 1h37m5.951644266s | 127.0.0.1 | GET /get.php?username=test&password=test&type=m3u_plus&output=ts

broken pipe comes from the requester, It's happen when client cut connection from server. (request timeout...etc) GIN manage this by recovering it. not a big issue don't worries
