### ISSUE TITLE
Can I serve multiple users from an IPTV account limited to one access per user?

### ISSUE THREAD

**Issue by bcashier** [pierre-emmanuelJ/iptv-proxy#28]
Hi,

Like in the title, can I serve multiple users to view channels from a limited iptv m3u link that support one access per user only ?

Thank you

**Comment by pierre-emmanuelJ** [comment]
Hello!

Yes can be a good idea! 🚀 

For the moment it's support only one user.

thanks

**Comment by bcashier** [comment]
Thank you, I am looking forward for this feature !

**Comment by hoshsadiq** [comment]
Just FYI, this would only be useful if IPTV provider's limits are set based on IP addresses, but more often than not, they limit you based on the number of connections. If it's the former, this could work, however, if it's the latter, you could in theory serve the same stream to multiple people, but you wouldn't be able to serve different streams at the same time, because the provider's server will likely cut off one of your streams.

**Comment by bcashier** [comment]
@hoshsadiq Yes, the goal is to serve one stream to multiple users without ability for example to switch channels, same one for all users.

And of course, must be one connection to IPTV provider (From one IP - Backend) and proxying the stream to multiple people so they watch same channel at the same time.

Thank you

**Comment by stedevo** [comment]
+1 for this feature but it would be nice, if the connection limit is configurable. Default could be 1 connection.

**Comment by Casburggraaf** [comment]
This would be Wonderfull. Would love to use this to watch sports witch friends together when in lockdown

**Comment by pierre-emmanuelJ** [comment]
Was busy on some projects, I'll try to work on this feature. The idea is also to have an user passthrought feature.
In your case @Casburggraaf since it's a proxy and it's end with a single IP, you can create an user when you setup the program and share these credentials with your friends and use the same, it will work.

**Comment by Casburggraaf** [comment]
My iptv provider has a ip lock and a single connection limit. Problem 1 is tackelt with this proxy(thanks, it really helps a lot!) The second problem is that only one user can watch something. But it can be possible I think for more users to watch the same channels but I don't now how to make it.
Right now if 2 users tries to watch the same channels it just switches from user 1 to 2.
<img width="559" alt="Screenshot 2021-01-15 at 11 42 41" src="https://user-images.githubusercontent.com/373753/104715431-d8a50800-5726-11eb-8433-e63f1eda6159.png">

**Comment by WolfganP** [comment]
You may try to restream it in your LAN with VLC multicast (don't transcode anything, just repack).

**Comment by hoshsadiq** [comment]
You can use tvheadend. It's a bit more involved setup, but once you get it setup it's great. You get the proxy functionality that this repo gives you + you can stream the same channel as many times as you want. In addition, it can do xmltv for you automatically if set up.

**Comment by pierre-emmanuelJ** [comment]
Duplicated: https://github.com/pierre-emmanuelJ/iptv-proxy/issues/72

**Comment by hurtauda** [comment]
Hello,
Are you working on #72 at the moment? Maybe I can contribute.
Also I am not sure #72 is a duplicate of #28, what I would really want is a way to force the number of active connections to 1:

My iptv provider is enforcing only 1 stream/connection at a time, but I would like to give this stream to multiple clients (multiple TV, same channel) using iptv-proxy.
I had tvheadend but it does not handle xtream very well + I had issues with SSL: https://tvheadend.org/issues/3388

Thank you

**Comment by adrianmihalko** [comment]
I don't even want to watch in the same time, but just I want that server should see one (my) IP. Situation: provider 1client/1stream, which is not problem, but I want to share these streams to my second home which has different IP:

<img width="447" alt="Screenshot 2022-01-17 at 19 15 37" src="https://user-images.githubusercontent.com/733361/149820353-524d514c-33b5-40d7-972a-8a008b4dda7f.png">

I would like to achieve that if any of subclient or mainclient is watching others should be blocked from connecting (first come first serve).

**Comment by pierre-emmanuelJ** [comment]
> I don't even want to watch in the same time, but I just want that provider should see one (my) IP. Situation: provider 1client/1stream, which is not problem, but I want to share these streams to my second home which has different IP:
> 
> <img alt="Screenshot 2022-01-17 at 19 15 37" width="447" src="https://user-images.githubusercontent.com/733361/149820353-524d514c-33b5-40d7-972a-8a008b4dda7f.png">
> 
> I would like to achieve that if any of subclient or mainclient is watching others should be blocked from connecting (first come first serve).

This can be possible, that's imply a lock on the server...etc, by design it's a bit rude, but maybe an additional flag could enable this feature.

The idea I had in the past was to bufferize "played channels" on the server to stream the same channel with multiple client on same connection to the original provider. Again, should not be by design but additional feature...

**Comment by steamyRayV** [comment]
I would love to replace xTeVe and this feature would do it. I don't think it would be rude in my use case. I have 5 stream slots and never use them all, maybe 3 at a time. What does happen often is two rooms watching the same channel and I save myself and my provider the bandwidth of multiple streams of the same broadcast. Also, xTeVe is doing this already so it's not like you would be putting out a new feature that would hurt providers.

Anyway, thanks for making and sharing this all!

**Comment by alebupal** [comment]
> Hello, Are you working on #72 at the moment? Maybe I can contribute. Also I am not sure #72 is a duplicate of #28, what I would really want is a way to force the number of active connections to 1:
> 
> My iptv provider is enforcing only 1 stream/connection at a time, but I would like to give this stream to multiple clients (multiple TV, same channel) using iptv-proxy. I had tvheadend but it does not handle xtream very well + I had issues with SSL: https://tvheadend.org/issues/3388
> 
> Thank you

I'm looking to do exactly the same thing: watch the same IPTV channel on multiple devices while only using one connection. Have you found anything? This is the only message I've found that refers to this.

Thanks!

**Comment by antebrl** [comment]
@alebupal and any other interested.
I made my own solution for this problem. Take a look at it: https://github.com/antebrl/IPTV-Restream

It caches the current (synchronized) stream.
If you find it helpful, please leave a ⭐

**Comment by adrianmihalko** [comment]
@antebrl Can't wait to try out, I will give you feedback later.
