### ISSUE TITLE
Configuration with docker and nginx 

### ISSUE THREAD

**Issue by tarek369** [pierre-emmanuelJ/iptv-proxy#29]
I have docker nginx and letsencrypt and it works as reverse proxy 

So basically when I http to my domain without a port, it automatically goes to the configured port 8080 to connect to the iptv proxy container . But that never worked.

Any ideas I just don't know how go works and the server on it so I couldn't debug much !!

**Comment by pierre-emmanuelJ** [comment]
I never tried the configuration with nginx + TLS letsencrypt. I can try ASAP and tell you more about that.

If you want to set up TLS more easily you can do it with traefik:
https://github.com/pierre-emmanuelJ/iptv-proxy#tls---https-with-traefik
just follow this two-step ;) and then `docker-compose up -d`!

then you will can access your iptv-proxy with:
`https://your-domain.com`.

**Comment by pierre-emmanuelJ** [comment]
Did you solve your issue?
