### ISSUE TITLE
config help for simple proxying

### ISSUE THREAD

**Issue by mpetre** [pierre-emmanuelJ/iptv-proxy#30]
Hi Pierre,

I copied the m3u list on a server locally and I can access it in vlc using URL http://view:summer5@10.10.11.10/tv4_list.m3u
I start iptv-proxy on the same machine that I tested vlc with this
/iptv-proxy \
--m3u-url http://view:summer5@10.10.11.10/tv4_list.m3u \
--port 6364 \
--hostname ubuntut420 \
--user test4 \
--password pswd4
but I get for all channels this message
[GIN-debug] GET    /test4/pswd4/live2/user_accnt/user_pswd/2127/index.m3u8 --> github.com/pierre-emmanuelJ/iptv-proxy/pkg/server.(*Config).reverseProxy-fm (4 handlers)

The tv4_list.m3u has links like this
http://play.ipdtvsystems.live/live2/user_accnt/user_pswd/15/index.m3u8

**Comment by pierre-emmanuelJ** [comment]
Hello 😃 Don't worry this is only Gin debug (debug from HTTP router). If you want to disable it you can just set this Env variable `GIN_MODE=release`

**Comment by mpetre** [comment]
Ohh I copied the wrong lines
[GIN-debug] GET    /test4/pswd4/invlid data  --> github.com/pierre-emmanuelJ/iptv-proxy/pkg/server.(*Config).reverseProxy-fm (4 handlers)
[GIN-debug] Listening and serving HTTP on :6364

I meant that when I use a m3u list that has links like this , the iptv-proxy works
http://iptv.rent:8080/user33/pswd33/5631

while when I use a m3u list that has links like this in not working
http://play.ipdtvsystems.live/live2/user22/pswd22/1/index.m3u8

Thank you

**Comment by pierre-emmanuelJ** [comment]
Hello :)

Sorry but we don't support m3u8 for playlist. But we support m3u8 with Xtream ;)

**Comment by pierre-emmanuelJ** [comment]
use it with Xtream it will work

**Comment by pierre-emmanuelJ** [comment]
Close due to inactivity
