### ISSUE TITLE
how config right?

### ISSUE THREAD

**Issue by lukinhanw** [pierre-emmanuelJ/iptv-proxy#31]
What i'm wrong ?

iptv-proxy --m3u-url http://35.188.137.65:25461/get.php?username=teste&password=teste&type=m3u_plus&output=m3u8 \
--port 8080 \
--hostname 35.238.135.70 \
--username test2222 \
--password 5a5a5a5

so in browser 
http://35.238.135.70:8080/iptv.m3u?username=test2222&password=5a5a5a5

give error 401

note: 35.238.135.70 is ip where i'm using the script

debug "[GIN] 2020/03/30 - 04:13:20 | 401 |       31.03µs | 179.232.137.132 | GET      /iptv.m3u?username=test2222&password=5a5a5a5"

**Comment by pierre-emmanuelJ** [comment]
I tried exactly the same configuration and it's work!
Can you try to GET this endpoint:
It acts as the same as `/iptv.m3u` but by xtream api style.
```
http://35.238.135.70:8080/get.php?username=test2222&password=5a5a5a5&type=m3u_plus&output=m3u8
```
To see what happens.

Thanks

**Comment by lukinhanw** [comment]
Hi! thanks for your attencption

I give this error when i use xtream api style
404 page not found

**Comment by pierre-emmanuelJ** [comment]
Are you sure the original provider work ?

**Comment by lukinhanw** [comment]
yes, its my link to

"14:15:29 | 404 | 2.14µs | 179.232.137.132 | GET      /get.php?username=teste&password=5a5a5a5&type=teste&output=m3u8"

do you have skype? or whatsapp ?

**Comment by lukinhanw** [comment]
Please, i'm have weeks try this

**Comment by lukinhanw** [comment]
hello!

**Comment by pierre-emmanuelJ** [comment]
Which version are you using?

**Comment by pierre-emmanuelJ** [comment]
Thanks I'll change for `username`. It's more consistent with the rest of the project.

For the next time make a `iptv-proxy --help` please:
```

Reverse proxy on iptv m3u file and xtream codes server api

Usage:
  iptv-proxy [flags]

Flags:
      --custom-endpoint string     custom endpoint "http://poxy.com/<custom-endpoint>/iptv.m3u"
  -h, --help                       help for iptv-proxy
      --hostname string            Hostname or IP to expose the IPTVs endpoints
      --https                      Activate https for urls proxy
      --iptv-proxy-config string   config file (default is $HOME/.iptv-proxy.yaml) (default "C")
      --m3u-cache-expiration int   M3U cache expiration in hour (default 1)
      --m3u-file-name string       name of the new proxified m3u file e.g "http://poxy.com/iptv.m3u" (default "iptv.m3u")
  -u, --m3u-url string             iptv m3u file or url e.g: "http://example.com/iptv.m3u"
      --password string            password UNSAFE(auth to access m3u proxy and xtream proxy) (default "passwordtest")
      --port int                   Port to expose the IPTVs endpoints (default 8080)
      --user string                user UNSAFE(temp auth to access proxy) (default "usertest")
      --xtream-base-url string     Xtream-code base url e.g(http://expample.tv:8080)
      --xtream-password string     Xtream-code password login
      --xtream-user string         Xtream-code user login
```
