### ISSUE TITLE
not permission

### ISSUE THREAD

**Issue by lukinhanw** [pierre-emmanuelJ/iptv-proxy#32]
i'm without permission when i'll download the iptv.m3u

**Comment by pierre-emmanuelJ** [comment]
is it a question?

**Comment by lukinhanw** [comment]
What i'm wrong ?

iptv-proxy --m3u-url http://35.188.137.65:25461/get.php?username=teste&password=teste&type=m3u_plus&output=m3u8
--port 8080
--hostname 35.238.135.70
--username test2222
--password 5a5a5a5

so in browser
http://35.238.135.70:8080/iptv.m3u?username=test2222&password=5a5a5a5

give error 401

note: 35.238.135.70 is ip where i'm using the script

debug "[GIN] 2020/03/30 - 04:13:20 | 401 | 31.03µs | 179.232.137.132 | GET /iptv.m3u?username=test2222&password=5a5a5a5"

**Comment by pierre-emmanuelJ** [comment]
Duplicate issue. I'll respond to the other issue:https://github.com/pierre-emmanuelJ/iptv-proxy/issues/31
