### ISSUE TITLE
Multiple Users

### ISSUE THREAD

**Issue by lukinhanw** [pierre-emmanuelJ/iptv-proxy#34]
its possible use multiple playlist, like:

http://35.188.137.65:25461/get.php?username=USER1&password=USER1&type=m3u_plus&output=mpegts

http://35.188.137.65:25461/get.php?username=USER2&password=USER2&type=m3u_plus&output=mpegts

....

in the same script?
i try do something but not success, thanks

**Comment by lukinhanw** [comment]
Hello sr?

**Comment by pierre-emmanuelJ** [comment]
hello look this 😃: https://github.com/pierre-emmanuelJ/iptv-proxy/issues/28
Maybe i'll add it when I have time

**Comment by pierre-emmanuelJ** [comment]
I'm closing due to a duplicate issue:
https://github.com/pierre-emmanuelJ/iptv-proxy/issues/28
