### ISSUE TITLE
parsing m3u file or xtream

### ISSUE THREAD

**Issue by riffraff2** [pierre-emmanuelJ/iptv-proxy#38]
Hello, 
my m3u provider sometimes write error in URL like "0http" or "0https". The application crash when it founds error.
The best, i think,  would be to bypass the error.

Thanks

**Comment by pierre-emmanuelJ** [comment]
Hello :)

I think not bypass the error but just log it into ‘stderr’.

I’ll look it ASAP thanks.

**Comment by riffraff2** [comment]
I'd love to, but I'm a very bad developer :)
