### ISSUE TITLE
HLS

### ISSUE THREAD

**Issue by lukinhanw** [pierre-emmanuelJ/iptv-proxy#39]
Hi, in HLS m3u8 dont work in output
HTTP ERROR 500

**Comment by pierre-emmanuelJ** [comment]
Hi, are you using hls with Xtream or just the m3u8 filke url?

if you are not using hls with xtream it's normal:
https://github.com/pierre-emmanuelJ/iptv-proxy/issues/14

**Comment by lukinhanw** [comment]
with xtream

**Comment by pierre-emmanuelJ** [comment]
Can you send logs, and give me a bit more context please? Thanks

**Comment by lukinhanw** [comment]
Show Error 500 on browser

**Comment by pierre-emmanuelJ** [comment]
what is the log in the iptv-proxy please? ;)

**Comment by pierre-emmanuelJ** [comment]
Closing due to an inactivity
