### ISSUE TITLE
[Question] Can I create a cache from iptv-proxy on my nvme ssd? 

### ISSUE THREAD

**Issue by CyberPoison** [pierre-emmanuelJ/iptv-proxy#43]
Hi,

I would like to know if I can create cache on my nvme ssd to have my streams enhanced in terms of speed and in loading times?

I would like to cache some 12GB on my nvme ssd to speed my loads and enhance my freezes and etc.. 

Can you tell me if I can do that on this script?

Regards

**Comment by pierre-emmanuelJ** [comment]
Hello :)

This Iptv-proxy don't do streams caching.

it can be a future option... :)

Thanks

**Comment by pierre-emmanuelJ** [comment]
Iptv-proxy have no plan to encode or bufferize stream on the disk.
