### ISSUE TITLE
[REQUEST] Separate TCP LISTEN Port and URL REWRITE Port

### ISSUE THREAD

**Issue by Olivier6767** [pierre-emmanuelJ/iptv-proxy#45]
I'm using your tool in docker thru a reverse proxy (Traefik) so I can make it available externally.
In my setup I only forward port 443 from my internet router to the TRAEFIK reverse proxy for all my services.
I would like to access the IPTV Proxy using a URL like:
`https://iptv.mydomain.com/`

However, in my setup the IPTV Proxy cannot listen to port 443 since it is used by another service (whi I cannot change).
I would like to setup IPTV Proxy to listen to another port like 8100.

The TRAEFIK labels would look like this:
```
- "traefik.http.routers.iptv.rule=Host(`iptv.mydomain.com`)"
- "traefik.http.routers.iptv.entrypoints=websecure"
- "traefik.http.routers.iptv.service=iptv"
- "traefik.http.services.iptv.loadbalancer.server.scheme=http"
- "traefik.http.services.iptv.loadbalancer.server.port=8100"
```

The IPTV Proxy settings would look like this:
```
- HOSTNAME=iptv.mydomain.com
- HTTPS=1
- PORT=8100            <== Setting only used for IPTV TCP Listen Port
- REWRITE_PORT=443     <== New setting used for URL Rewrite - blank should be allowed
```

The ITPV Proxy would generate stream URLs like this:
`https://iptv.mydomain.com:443/MY_USER/MY_PASSWORD/<Stream_ID>`

However the TCP Porxy would listen to the **port 8100** in the docker container.

TRAEFIK will receive the request on **port 443** and pass it back to the IPTV Proxy container on **port 8100**.

By allowing blank value for REWRITE_PORT, the URL would look like this:
With HTTPS=1: `https://iptv.mydomain.com/MY_USER/MY_PASSWORD/<Stream_ID>`   **<== Sent to port 443**
With HTTPS=0: `http://iptv.mydomain.com/MY_USER/MY_PASSWORD/<Stream_ID>`      **<== Sent to port 80**

Thanks for considering this change.

**Comment by pierre-emmanuelJ** [comment]
Hello ☺️

Yes thanks I see the problem, I’ll try to make a patch ASAP.

**Comment by Olivier6767** [comment]
Hello,
Great, Thank you for your support!
Quick additional question: what is the format of the file to be used with the option` --iptv-proxy-config` ?
Can you provide an example?

I've made some tests as a way to easily override my default settings from the docker-compose Environment strings, but it seems that some settings from the file are not taken into account.
I may have the format of the file wrong, therefore an example would be helpfull.

Thanks again!

**Comment by jamespo** [comment]
@Olivier6767 I've implemented this functionality in my fork @ https://github.com/jamespo/iptv-proxy

There is an additional command line flag --advertised-port [num],  this is returned to the browser in URLs but can be different from the --port value.

**Comment by pierre-emmanuelJ** [comment]
@jamespo  and @Olivier6767 implemented in https://github.com/pierre-emmanuelJ/iptv-proxy/pull/77

I'll update the doc

**Comment by pierre-emmanuelJ** [comment]
doc updated: https://github.com/pierre-emmanuelJ/iptv-proxy/commit/a763cdaadf4fb7a30ce4969742e34339558b916b
