### ISSUE TITLE
Request: Pass-trough username & password to the proxified back-end

### ISSUE THREAD

**Issue by Znuff** [pierre-emmanuelJ/iptv-proxy#49]
Hello,

Is there any chance to have this work in a "proper" proxy that actually (re)uses the username/password that it gets called on?

What I mean, for the sake of example:

```
http://iptv-proxy.tld/iptv.m3u?username=$username&password=$password

=>

http://xc-backend.tld/get.php?username=$username&password=$password
```

This would actually be useful in a few scenarios, like hiding the original XtreamCodes Server's URL.

**Comment by pierre-emmanuelJ** [comment]
Hello :) 
If you are using the iptv-proxy with the xtream mode, the original url or user/pass doesn't appear in the file or request.

`/get.php` is also available instead of `/iptv.m3u` you can keep the same query param as the original provider.

e.g: `http://iptv-proxy.example.com:8080/get.php?...etc`

**Comment by Znuff** [comment]
That's not what I asked.

Right now when running with XtreamCodes backend, you set up a specific username/password to be sent to the backend (ie: `--xtream-password` and `--xtream-user`).

You also set up a "local" username/pass via `--user` and `--password`, which allows access to the proxy itself.

My request is more of, like, **what if the username/password received from the client/end-user would actually be sent directly to the XtreamCodes backend**?

**Comment by pierre-emmanuelJ** [comment]
Okay! I got it now after re-reading the issue ;)
For the moment xtream user credentials pass-trought is not supported by default.
I put in it the todo-list to add the option or feel free to open a PR 😃

**Comment by pierre-emmanuelJ** [comment]
duplicated: https://github.com/pierre-emmanuelJ/iptv-proxy/issues/72
we will support it
