### ISSUE TITLE
error unmarshaling json when using xtream proxy

### ISSUE THREAD

**Issue by jk7gr** [pierre-emmanuelJ/iptv-proxy#51]
Dear Pierre-Emmanuel,
I love your project. I tried the docker version of it and managed to have a container on my Synology NAS.
I have loaded the desired playlist and I have managed to open it properly on VLC. 
However, the problem is when I use the xstream proxy part. I particular when I add the credentials in the LXStream android app I get "Network Error". The log on the server is below:

_[GIN] 2020/09/04 - 22:16:17 | 500 |   4.13636976s |      172.19.0.1 | GET      /player_api.php?username=xxxxx&password=xxxxx
Error #01: error unmarshaling json: json: invalid use of ,string struct tag, trying to unmarshal unquoted value into int_

At this stage I don't know anything more I can do. Your assistance will be highly appreciated.
Thank you!

**Comment by pierre-emmanuelJ** [comment]
Hello thanks for reporting your issue :) I'll look at it ASAP

**Comment by jk7gr** [comment]
It works now.
