### ISSUE TITLE
Live works fine, VOD does not

### ISSUE THREAD

**Issue by sebastien4** [pierre-emmanuelJ/iptv-proxy#53]
Thanks a lot for this great tool.

Everything works fine for live streams, but it fails with VOD assets.
Got code 200 for mkv when hitting play, and then black screen and buffering.

I checked with original URL and it works.

Any idea? Sth related to the provider?

Thanks.

**Comment by pierre-emmanuelJ** [comment]
Hello, Thanks :)

Can you provide me some logs from the program, please?

Thank you

**Comment by sebastien4** [comment]
You can close this one, issue is related to internal app player.
My bad..

**Comment by pierre-emmanuelJ** [comment]
No problem, thanks

**Comment by sebastien4** [comment]
I'll try to deep dive into this one because it's really painful.

Issue is related to ExoPlayer not playing on demand streams correctly.
Both VOD and timeshift streams are concerned..

**Comment by pierre-emmanuelJ** [comment]
Thanks to take time :)
