### ISSUE TITLE
not geting playlist

### ISSUE THREAD

**Issue by BoBi1234** [pierre-emmanuelJ/iptv-proxy#54]
Basically, what I'm doing wrong? I starting app wit below command, at first I have some issues with --port but after ading '' to m3u-url it seems fine.

 `iptv-proxy --m3u-url 'http://SERVERIP:PORT/get.php?username=USERNAME&password=PASSWORD&output=ts&type=m3u&output=m3u8'  --port 7070 --hostname MYIP --xtream-user USERNAME --xtream-password PASSWORD --xtream-base-url http://SERVERIP:PORT --user test --password passwordtest`

after that I'm receiving  `[GIN-debug] GET    /iptv.m3u                 --> github.com/pierre-emmanuelJ/iptv-proxy/pkg/server.(*Config).xtreamGetAuto-fm (5 handlers)
[GIN-debug] POST   /iptv.m3u                 --> github.com/pierre-emmanuelJ/iptv-proxy/pkg/server.(*Config).xtreamGetAuto-fm (5 handlers)
[GIN-debug] Listening and serving HTTP on :7070
` in console but when try to download new list web browser connot reach site. I'm not really familiar with linux, know only basics so it might be my fault :)

**Comment by pierre-emmanuelJ** [comment]
did you try to access this url:
```Shell
curl http://MYIP:MYPORT/get.php?username=test&password=passwordtest&output=ts&type=m3u&output=m3u8
```

you are using port `7070` to reach the iptv-proxy, be sure this port is open on your machine, firewall, or provider level...etc

Thnaks

**Comment by BoBi1234** [comment]
Hi,

yeah you was right, firewall issue, dont know why I didnt check it. 
but have a question, is there any chance to proxy few m3u? I have few "clients" as a reseller, I would like to proxyfie them through my server. Only idea I have as for now is to run few instance of proxy but each of them will required its own port. What would be perfect for me is have one instance running with few logins/passwords. any idea if it can be done easily?

**Comment by pierre-emmanuelJ** [comment]
Hi, okay nice you found your issue :)
for the multiple user referring to this issue:
https://github.com/pierre-emmanuelJ/iptv-proxy/issues/28
This feature request is not implemented yet, hopefully one day ;)

Stay aware of it by looking repo's notification ;)
