### ISSUE TITLE
release mode

### ISSUE THREAD

**Issue by cireap** [pierre-emmanuelJ/iptv-proxy#55]
Hi, how are you?
i need to call iptv-proxy through a script.sh - but the scrip stop on iptv-proxy and does not go to the next one. is this because iptv-proxy is in debug mode? docker-compose.yml is already release-mode. how do I run in release-mode?

**Comment by pierre-emmanuelJ** [comment]
Hello, iptv-proxy sould be run as a daemon or a service. 
The binary itself output on `stdout` and stay on it.
if you want to demonize it, you can use Docker or docker-compose or also Systemd to create a daemon service.

Thank you :)

**Comment by Juancollado2003** [comment]
> Hi, how are you? i need to call iptv-proxy through a script.sh - but the scrip stop on iptv-proxy and does not go to the next one. is this because iptv-proxy is in debug mode? docker-compose.yml is already release-mode. how do I run in release-mode?

In my script I used "iptv-proxy whatever --port 80" &> /dev/null & and to kill the session I just kill the port by "fuser -n tcp -k 80"
