### ISSUE TITLE
problem in generating the list

### ISSUE THREAD

**Issue by cireap** [pierre-emmanuelJ/iptv-proxy#56]
Hi.
I can't generate an output list correctly.
the only way to run is like this:

 iptv-proxy --hostname 127.0.0.1 --m3u-url listiptv.m3u --port 8086 --user user621 --password pass621
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env: export GIN_MODE = release
 - using the code: gin.SetMode (gin.ReleaseMode)

[GIN-debug] GET /iptv.m3u -> github.com/pierre-emmanuelJ/iptv-proxy/pkg/server.(*Config).getM3U-fm (5 handlers)
[GIN-debug] POST /iptv.m3u -> github.com/pierre-emmanuelJ/iptv-proxy/pkg/server.(*Config).getM3U-fm (5 handlers)
[GIN-debug] GET / user621 / pass621 / SWN0QEC5 / BrunoCligor76 / 5116 -> github.com/pierre-emmanuelJ/iptv-proxy/pkg/server.(*Config).reverseProxy-fm (4 manipulators)
[GIN-debug] Listening and serving HTTP at: 8086

original list:
http://iptvserver:80/SWN0QEC5/BrunoCligor76/5116

generated list:
http://127.0.0.1:8084/SWN0QEC5/BrunoCligor76/5116

but as in the log the iptv-proxy:
[GIN-debug] GET /user621/pass621/SWN0QEC5/BrunoCligor76/5116 ->

if I don't add:
/user621/pass621 /
the list generated the streaming does not work.
thus being edited manually:
http://127.0.0.1:8084/usuario621/pass621/SWN0QEC5/BrunoCligor76/170241

tried it by docker, installing the .deb file and by tar.gz
the same problem happens

my system:
ubuntu 16.04 lts server

Sorry for my bad english

**Comment by Gudio** [comment]
I have the same issue. Start command:
`./iptv-proxy --m3u-url iptv/playlist.m3u --port 8080 --user username --password password`

Generated playlist (iptv.m3u):
`http://host:8080/streamuser/streampassword/1000`
which returns 404, but if I insert custom credentials:
`http://host:8080/username/password/streamuser/streampassword/1000`
it works.

**Comment by pierre-emmanuelJ** [comment]
it was a regression bug! your issue is fixed in this PR https://github.com/pierre-emmanuelJ/iptv-proxy/pull/75
(hard to find time to write unit tests now)
