### ISSUE TITLE
Problème installation sur DS918+

### ISSUE THREAD

**Issue by tony77682** [pierre-emmanuelJ/iptv-proxy#58]
Bonjour,

j'ai essayé d'installer votre image iptv-proxy sur mon ds918+.
j'ai bien créé le fichier amce.json et traefik.toml.
Quand je lance les 2 conteneurs : dans traefik j'obtiens "no log aviable".
et le conteneur iptv-proxy ne démarre pas.

pouvez-vous m'aider?

merci

**Comment by pierre-emmanuelJ** [comment]
Hello, Can you  provide your docker-copose, and the rest of your config, if you not solved your issue
Thanks
