### ISSUE TITLE
panic on duplicate entries

### ISSUE THREAD

**Issue by andersonrfsilva** [pierre-emmanuelJ/iptv-proxy#6]
When my list have a duplicate entries I got a panic and application closes:

[GIN-debug] GET    /movie/FIVEVOD0419/jL7FXAdJhl/5043.mp4 --> routes.github_com_pierre_emmanuelJ_iptv_proxy_pkg_routes..thunk11 (5 handlers)
[GIN-debug] GET    /movie/FIVEVOD0419/jL7FXAdJhl/15057.mp4 --> routes.github_com_pierre_emmanuelJ_iptv_proxy_pkg_routes..thunk11 (5 handlers)
[GIN-debug] GET    /movie/FIVEVOD0419/jL7FXAdJhl/3655.mp4 --> routes.github_com_pierre_emmanuelJ_iptv_proxy_pkg_routes..thunk11 (5 handlers)
[GIN-debug] GET    /movie/FIVEVOD0419/jL7FXAdJhl/3655.mp4 --> routes.github_com_pierre_emmanuelJ_iptv_proxy_pkg_routes..thunk11 (5 handlers)
panic: handlers are already registered for path '/movie/FIVEVOD0419/jL7FXAdJhl/3655.mp4'

goroutine 1 [running]:
panic
        ../../../src/libgo/go/runtime/panic.go:554
github_com_pierre_emmanuelJ_iptv_proxy_vendor_github_com_gin_gonic_gin.node.addRoute
        /root/go/src/github.com/pierre-emmanuelJ/iptv-proxy/vendor/github.com/gin-gonic/gin/tree.go:235
github_com_pierre_emmanuelJ_iptv_proxy_vendor_github_com_gin_gonic_gin.Engine.addRoute
        /root/go/src/github.com/pierre-emmanuelJ/iptv-proxy/vendor/github.com/gin-gonic/gin/gin.go:252
github_com_pierre_emmanuelJ_iptv_proxy_vendor_github_com_gin_gonic_gin.RouterGroup.handle
        /root/go/src/github.com/pierre-emmanuelJ/iptv-proxy/vendor/github.com/gin-gonic/gin/routergroup.go:71
github_com_pierre_emmanuelJ_iptv_proxy_vendor_github_com_gin_gonic_gin.RouterGroup.GET
        /root/go/src/github.com/pierre-emmanuelJ/iptv-proxy/vendor/github.com/gin-gonic/gin/routergroup.go:99
github_com_pierre_emmanuelJ_iptv_proxy_pkg_routes.Routes
        /root/go/src/github.com/pierre-emmanuelJ/iptv-proxy/pkg/routes/routes.go:75
github_com_pierre_emmanuelJ_iptv_proxy_pkg_routes.Serve
        /root/go/src/github.com/pierre-emmanuelJ/iptv-proxy/pkg/routes/routes.go:37
cmd.func1
        /root/go/src/github.com/pierre-emmanuelJ/iptv-proxy/cmd/root.go:52
github_com_pierre_emmanuelJ_iptv_proxy_vendor_github_com_spf13_cobra.Command.execute
        /root/go/src/github.com/pierre-emmanuelJ/iptv-proxy/vendor/github.com/spf13/cobra/command.go:766
github_com_pierre_emmanuelJ_iptv_proxy_vendor_github_com_spf13_cobra.Command.ExecuteC
        /root/go/src/github.com/pierre-emmanuelJ/iptv-proxy/vendor/github.com/spf13/cobra/command.go:852
github_com_pierre_emmanuelJ_iptv_proxy_vendor_github_com_spf13_cobra.Command.Execute
        /root/go/src/github.com/pierre-emmanuelJ/iptv-proxy/vendor/github.com/spf13/cobra/command.go:800
github_com_pierre_emmanuelJ_iptv_proxy_cmd.Execute
        /root/go/src/github.com/pierre-emmanuelJ/iptv-proxy/cmd/root.go:61
main.main
        /root/go/src/github.com/pierre-emmanuelJ/iptv-proxy/main.go:6

**Comment by pierre-emmanuelJ** [comment]
thanks to report this issue.

So it's come from GIN because it try to duplicate endpoint.
My suggestion is to return an error when an entry is duplicated.

If you have any idea don't hesitate thanks 👍

**Comment by andersonrfsilva** [comment]
I comment out follow lines in gin-gonic/gin/tree.go file and works to me :-)

if n.handlers != nil {
      panic("handlers are already registered for path '" + fullPath + "'")
}

I guess better notify duplicated but not return error, for example, I can't fix the list of my provider if your software close with error is unusable to me.

Thanks for your time.

**Comment by pierre-emmanuelJ** [comment]
if you comment this following code you will ignore all the previous duplicated handlers.
I think it's not the way to solve the problem with this hack.

why not catch it at handler creation and display a warning saying:
dirty example:
`Warning: track ID skipped du to a duplicated URL/endpoint or whatever...`

**Comment by andersonrfsilva** [comment]
sorry but i dunno Go language to do this, but your ideia looks like good.

**Comment by pierre-emmanuelJ** [comment]
when this conflict is met now:

```
[iptv-proxy] WARNING endpoint "track-test-42" already exist, skipping it
```
