### ISSUE TITLE
does not open link

### ISSUE THREAD

**Issue by MOPO3KO** [pierre-emmanuelJ/iptv-proxy#65]
Hello!
I use a translator, so I apologize for the correct wording.
The provider has a playlist that the proxy does not accept.
I will give the link itself and part of the list (passwords changed)
`http://playlist.saphir.tv/get.php?username=saphiruser&password=6LBC3N1EIR&type=m3u&output=hls`

Here is the playlist.m3u file:

`#EXTM3U url-tvg="http://account.saphir.tv/epg.xml.gz"
#EXTINF:-1 timeshift="7" catchup-days="7" catchup-type="flussonic" tvg-id="viasat-explore"  group-title="Познавательные" tvg-logo="http://playlist.saphir.tv:80/icon/91.png.png",Viasat Explore HD
http://fra.saphir.tv/3139/index.m3u8?username=saphiruser&password=6LBC3N1EIR&token=6e06d6f2f8851582fc0d373dc262360e&ch_id=91&req_host=MRgV5y
#EXTINF:-1 timeshift="7" catchup-days="7" catchup-type="flussonic" tvg-id="pobeda"  group-title="Кино и сериалы" tvg-logo="http://playlist.saphir.tv:80/icon/580.png.png",Победа
http://fra.saphir.tv/8934/index.m3u8?username=saphiruser&password=6LBC3N1EIR&token=6e06d6f2f8851582fc0d373dc262360e&ch_id=580&req_host=MRgV5y
#EXTINF:-1 timeshift="7" catchup-days="7" catchup-type="flussonic" tvg-id="football-ru"  group-title="Спортивные" tvg-logo="http://playlist.saphir.tv:80/icon/237.png.png",Футбол HD
http://fra.saphir.tv/2647/index.m3u8?username=saphiruser&password=6LBC3N1EIR&token=6e06d6f2f8851582fc0d373dc262360e&ch_id=237&req_host=MRgV5y
#EXTINF:-1 timeshift="7" catchup-days="7" catchup-type="flussonic" tvg-id="sts"  group-title="Общие" tvg-logo="http://playlist.saphir.tv:80/icon/7.png.png",СТС
http://fra.saphir.tv/9716/index.m3u8?username=saphiruser&password=6LBC3N1EIR&token=6e06d6f2f8851582fc0d373dc262360e&ch_id=7&req_host=MRgV5y
#EXTINF:-1 timeshift="7" catchup-days="7" catchup-type="flussonic" tvg-id="zagorodnaya-zhizn"  group-title="Познавательные" tvg-logo="http://playlist.saphir.tv:80/icon/548.png.png",Загородная жизнь
http://fra.saphir.tv/3366/index.m3u8?username=saphiruser&password=6LBC3N1EIR&token=6e06d6f2f8851582fc0d373dc262360e&ch_id=548&req_host=MRgV5y
#EXTINF:-1 timeshift="0" catchup-days="0" catchup-type="flussonic" tvg-id="vh1-european"  group-title="Музыкальные" tvg-logo="http://playlist.saphir.tv:80/icon/224.png.png",VH1 European
http://fra.saphir.tv/8870/index.m3u8?username=saphiruser&password=6LBC3N1EIR&token=6e06d6f2f8851582fc0d373dc262360e&ch_id=224&req_host=MRgV5y
#EXTINF:-1 timeshift="7" catchup-days="7" catchup-type="flussonic" tvg-id="pervy"  group-title="Общие" tvg-logo="http://playlist.saphir.tv:80/icon/309.png.png",Первый
http://fra.saphir.tv/9195/index.m3u8?username=saphiruser&password=6LBC3N1EIR&token=6e06d6f2f8851582fc0d373dc262360e&ch_id=309&req_host=MRgV5y
#EXTINF:-1 timeshift="0" catchup-days="0" catchup-type="flussonic" tvg-id="lrt-tv"  group-title="Литовские" tvg-logo="http://playlist.saphir.tv:80/icon/450.png.png",LRT
http://fra.saphir.tv/3733/index.m3u8?username=saphiruser&password=6LBC3N1EIR&token=6e06d6f2f8851582fc0d373dc262360e&ch_id=450&req_host=MRgV5y`

`[GIN-debug] [WARNING] Now Gin requires Go 1.6 or later and Go 1.7 will be required soon.
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)
[GIN-debug] GET    /get.php                  --> github.com/pierre-emmanuelJ/iptv-proxy/pkg/server.(*Config).xtreamGet-fm (5 handlers)
[GIN-debug] POST   /get.php                  --> github.com/pierre-emmanuelJ/iptv-proxy/pkg/server.(*Config).xtreamGet-fm (5 handlers)
[GIN-debug] GET    /player_api.php           --> github.com/pierre-emmanuelJ/iptv-proxy/pkg/server.(*Config).xtreamPlayerAPIGET-fm (5 handlers)
[GIN-debug] POST   /player_api.php           --> github.com/pierre-emmanuelJ/iptv-proxy/pkg/server.(*Config).xtreamPlayerAPIPOST-fm (5 handlers)
[GIN-debug] GET    /xmltv.php                --> github.com/pierre-emmanuelJ/iptv-proxy/pkg/server.(*Config).xtreamXMLTV-fm (5 handlers)
[GIN-debug] GET    /test/testpassword/:id    --> github.com/pierre-emmanuelJ/iptv-proxy/pkg/server.(*Config).xtreamStream-fm (4 handlers)
[GIN-debug] GET    /live/test/testpassword/:id --> github.com/pierre-emmanuelJ/iptv-proxy/pkg/server.(*Config).xtreamStreamLive-fm (4 handlers)
[GIN-debug] GET    /movie/test/testpassword/:id --> github.com/pierre-emmanuelJ/iptv-proxy/pkg/server.(*Config).xtreamStreamMovie-fm (4 handlers)
[GIN-debug] GET    /series/test/testpassword/:id --> github.com/pierre-emmanuelJ/iptv-proxy/pkg/server.(*Config).xtreamStreamSeries-fm (4 handlers)
[GIN-debug] GET    /hlsr/:token/test/testpassword/:channel/:hash/:chunk --> github.com/pierre-emmanuelJ/iptv-proxy/pkg/server.(*Config).hlsrStream-fm (4 handlers)
[GIN-debug] GET    /iptv.m3u                 --> github.com/pierre-emmanuelJ/iptv-proxy/pkg/server.(*Config).xtreamGetAuto-fm (5 handlers)
[GIN-debug] POST   /iptv.m3u                 --> github.com/pierre-emmanuelJ/iptv-proxy/pkg/server.(*Config).xtreamGetAuto-fm (5 handlers)
[GIN-debug] Listening and serving HTTP on :8081`

Tell me what you can fix to work with such a list?

**Comment by MOPO3KO** [comment]
if I go to the proxy, I get the following file:

`
#EXTM3U
#EXTINF:-1 timeshift="0" catchup-days="0" catchup-type="flussonic" tvg-id="musicbox-ua-hd" group-title="Украинские" tvg-logo="http://playlist.saphir.tv:80/icon/511.png.png", Musicbox
http://192.168.1.10:8081/9482/index.m3u8
#EXTINF:-1 timeshift="7" catchup-days="7" catchup-type="flussonic" tvg-id="sony-turbo" group-title="Кино и сериалы" tvg-logo="http://playlist.saphir.tv:80/icon/142.png.png", Sony Turbo
http://192.168.1.10:8081/1490/index.m3u8
#EXTINF:-1 timeshift="0" catchup-days="0" catchup-type="flussonic" tvg-id="nashe-novoe-kino" group-title="Кино и сериалы" tvg-logo="http://playlist.saphir.tv:80/icon/712.png.png", Наше новое кино
http://192.168.1.10:8081/1388/index.m3u8
#EXTINF:-1 timeshift="0" catchup-days="0" catchup-type="flussonic" tvg-id="indigo-ua" group-title="Украинские" tvg-logo="http://playlist.saphir.tv:80/icon/744.png.png", Индиго HD UA PREMIUM+
http://192.168.1.10:8081/7135/index.m3u8
#EXTINF:-1 timeshift="0" catchup-days="0" catchup-type="flussonic" tvg-id="setanta-sports" group-title="Спортивные" tvg-logo="http://playlist.saphir.tv:80/icon/641.png.png", Setanta Sports 1
http://192.168.1.10:8081/5528/index.m3u8
`

**Comment by pierre-emmanuelJ** [comment]
Hello, m3u8 playlist is not supported by the proxy.
Only m3u for the moment.

> http://playlist.saphir.tv/get.php?username=saphiruser&password=6LBC3N1EIR&type=m3u&output=hls

it's seems you are using an xtream provider, which is compatible HLS with the iptv-proxy.

If you use the xtream API app...etc you can  stream as hls.

otherwise, to be full compatible you can try to use:

```
http://playlist.saphir.tv/get.php?username=saphiruser&password=6LBC3N1EIR&type=m3u_plus&output=ts
```

**Comment by pierre-emmanuelJ** [comment]
Late reply I close it because it is old.

Feel free to reopen it if it's needed
