### ISSUE TITLE
Multiple Docker images

### ISSUE THREAD

**Issue by codigus** [pierre-emmanuelJ/iptv-proxy#71]
Hi, It is possible to run multiple times the docker image? I would like to connect about 150 persons to the proxy using the same xtream server but with different usernames from xtream codes and new ones in the proxy? Somebody can help me in this solution? I would be really grateful.

**Comment by MCTyler** [comment]
Just change the Port.....

**Comment by codigus** [comment]
> Just change the Port.....

yeah, i already figure that. But my idea was my clients get a server each one and connect my service through each individual proxy. And if i was able to run run multiple users with same port would be wonderful. But thanks for your reply.

**Comment by MCTyler** [comment]
> 
> 
> > Just change the Port.....
> 
> yeah, i already figure that. But my idea was my clients get a server each one and connect my service through each individual proxy. And if i was able to run run multiple users with same port would be wonderful. But thanks for your reply.

Might be better off to just become a reseller.....

**Comment by pierre-emmanuelJ** [comment]
Hello, for the moment the iptv-proxy doesn't support multiple user or credentials passthrough to the API.
It is in the roadmap when I'll have time :)

Stay aware of new future release for that ;)

Thanks

**Comment by hjaltioj** [comment]
Hi
I have made two dockers. one with port 8080 and one with 8081
cant get the one with the port 8081 working?? name and port only things that i changed
