### ISSUE TITLE
Xtream API Issue

### ISSUE THREAD

**Issue by codigus** [pierre-emmanuelJ/iptv-proxy#74]
Hello,

In some devices like app xciptv or other set top boxes when I connect through API the channels doesn't show. 
Other thing, in set top boxes Formuler Z+ or Nano using MyTvOnline with API when I play channels without EPG the portal restart. there is anything that i can do?

Errors in XC IPTV:
![Captura de ecrã 2021-03-18, às 02 26 25](https://user-images.githubusercontent.com/69589417/111564530-c466a100-8791-11eb-8c62-d5dac4c476ff.png)

Tks a lot

**Comment by pierre-emmanuelJ** [comment]
hello @codigus , can you try the latest release: https://github.com/pierre-emmanuelJ/iptv-proxy/releases/tag/v3.1.1
And see if the problem persist?

**Comment by codigus** [comment]
@pierre-emmanuelJ Still the same, I already update for latest version. With some APP's the connection with API still giving me problems. I think it's the way the request is made by the app. Other ones work ok. If I configure with m3u works well everywhere... I own my provider too. :)

**Comment by pierre-emmanuelJ** [comment]
As I can see in logs connection is reset by the peer.

Maybe a timeout on the request in your player and the connection is closed be it.

As I have no more information on your issue, it's seems not related to the proxy but to the player.

Can you close the issue if it's ok for you.

Thank you.
