### ISSUE TITLE
Docker Image -  arm64

### ISSUE THREAD

**Issue by p418** [pierre-emmanuelJ/iptv-proxy#78]
Hi @pierre-emmanuelJ !

Since I'm running iptv-proxy on a rpi4 (and maybe not the only one), there would be a chance add `arm64/v8` arch image release on docker hub?

This would save me from having to rebuild the image from source for each new release.

btw, thanks for your work!

**Comment by pierre-emmanuelJ** [comment]
I'm working on it:
https://github.com/pierre-emmanuelJ/iptv-proxy/commit/45d3ac37f29d3ed31bf2b7c073102e8def3e6478

**Comment by p418** [comment]
great, merci!

**Comment by pierre-emmanuelJ** [comment]
@p418 the CI/CD  now build arm64 also automagically!
The latest release with arm:
https://github.com/pierre-emmanuelJ/iptv-proxy/releases/tag/v3.3.0
