### ISSUE TITLE
HTTP Status 401 when trying to stream

### ISSUE THREAD

**Issue by goldelehr** [pierre-emmanuelJ/iptv-proxy#80]
Hi,

i managed to proxy my M3U file and open it locally in VLC. After clicking on a channel IPTV-Proxy give an error 401. 

This is the command i use to start iptv-proxy:

`iptv-proxy --hostname my.host.name --user my-local-username --password my-local-password --port 7010 --m3u-url "http://the.source.stream.url:8912/get.php?username=the-source-username&password=the-source-password&output=ts&type=m3u"`

The playlist i get via iptv-proxy looks okay:

```
#EXTM3U
#EXTINF:-1 , Channel A
http://my.host.name:7010/my-local-username/my-local-password/1121
#EXTINF:-1 , Channel B
http://my.host.name:7010/my-local-username/my-local-password/1122
```

This is what it looks like on the command line:

![image](https://user-images.githubusercontent.com/404557/113886979-61c95980-97c1-11eb-8fc5-ff139c8b5b5f.png)

Thanks for your help!

**Comment by pierre-emmanuelJ** [comment]
Is it working with your original playlist with VLC? As I see in the log the `401` comes from your provider.

**Comment by goldelehr** [comment]
@pierre-emmanuelJ You are right, looks like the service provider is restricted to my home ip and i can't proxy it via my server. Sorry for bothering you and thanks for your help!
