### ISSUE TITLE
Support for /play-Format urls

### ISSUE THREAD

**Issue by tefinger** [pierre-emmanuelJ/iptv-proxy#83]
First of all thank you very much for your work on this project. It's great and I'm using it for a long time now without any issues.

Till now ... :-) My IPTV provider changed the url format from `/<user>/<pass>/<id>` to `/play/<some-kind-of-token>/ts`.
This causes that I'm no longer able to use iptv-proxy for the streams.
iptv-proxy just gives an 404 error when trying to stream.

Is it possible to add support for that kind of urls?

**Comment by pierre-emmanuelJ** [comment]
Thanks for your issue! 
Yes could be possible. Is your provider using xtream API?

**Comment by tefinger** [comment]
Yes I think so. I have no concrete statement from the provider but the urls etc. look like he does.

**Comment by pierre-emmanuelJ** [comment]
Hello @tefinger,

Yes it could be quick when I have time, stay aware of next changes ;)

**Comment by shrimpydown** [comment]
Is it possible to play these urls or is there a workaround available? Thanks!

**Comment by mrparsons** [comment]
My provider has also changed to this "/play/token" method, and no, it doesnt seem iptv-proxy supports that yet.

**Comment by tefinger** [comment]
I  made a workaround which can be found here:
https://github.com/tefinger/iptv-proxy/commit/5f8b49af0f2b83e8707f862daa6d3f2be45ea03e
It's a bit hacky, so I decided to not submit it as a PR

**Comment by pierre-emmanuelJ** [comment]
> tefinger@5f8b49a

Thanks, for the pending fix :) BTW you did a breaking change for the HLS support in your patch.

I'll do a change this week, to release a new version.

**Comment by pierre-emmanuelJ** [comment]
I opened a PR https://github.com/pierre-emmanuelJ/iptv-proxy/pull/118
The new release will be process automatically after I merged and create a new tag.

New release will be out today!

**Comment by pierre-emmanuelJ** [comment]
the right change on master: https://github.com/pierre-emmanuelJ/iptv-proxy/commit/1e0dc9edcb5879e127ffcfa02059d1a3b4711030

**Comment by pierre-emmanuelJ** [comment]
Release is out now!
https://github.com/pierre-emmanuelJ/iptv-proxy/releases/tag/v3.7.0
