### ISSUE TITLE
m3u8 streams will not play

### ISSUE THREAD

**Issue by MCTyler** [pierre-emmanuelJ/iptv-proxy#86]
Here's the log output when they try to play.
```
[GIN] 2021/05/30 - 12:57:27 | 404 |    134.0871ms |      172.17.0.1 | GET      /test/test/subtitlelist_leng.m3u8


[GIN] 2021/05/30 - 12:57:27 | 404 |    139.4495ms |      172.17.0.1 | GET      /test/test/subtitlelist_leng.m3u8


[GIN] 2021/05/30 - 12:57:27 | 404 |    137.5015ms |      172.17.0.1 | GET      /test/test/chunklist.m3u8


[GIN] 2021/05/30 - 12:57:27 | 404 |     137.773ms |      172.17.0.1 | GET      /test/test/chunklist.m3u8
```

Any work-around?

**Comment by MCTyler** [comment]
I think this will fix it...gotta test.....
![image](https://user-images.githubusercontent.com/6390898/120108656-cd79d400-c12b-11eb-8223-aadca1047e64.png)

routes.go file

**Comment by MCTyler** [comment]
Issued fixed with latest by [https://github.com/LePresidente] LePresidente. Please Pull and Merge.

**Comment by pierre-emmanuelJ** [comment]
This one:
https://github.com/LePresidente/iptv-proxy/commit/9390d0d632b76678fc76b0826b359cff2f33b088

I'll review the code before
