### ISSUE TITLE
configfile User overwrited by sudo

### ISSUE THREAD

**Issue by Azureit** [pierre-emmanuelJ/iptv-proxy#88]
I tested running iptv-proxy as user _nobody_,
**sudo -u nobody ./iptv-proxy --iptv-proxy-config test.yml**

The **User** flag inside test.yml is overwritten by the username specified to run iptv-proxy as, in this case _nobody_

EDIT
My workaround is to add to the command line --user myuser
now the command is:
**sudo -u nobody ./iptv-proxy --iptv-proxy-config test.yml --user myuser**

**Comment by pierre-emmanuelJ** [comment]
Yes this is a typo on my side, I should rename the flag/env `user` to `username`.
