### ISSUE TITLE
Unable to proxy xtream codes service

### ISSUE THREAD

**Issue by itsneil** [pierre-emmanuelJ/iptv-proxy#9]
Running the prebuild version 1.1.0 on an Ubuntu machine...

`iptv-proxy --m3u-url "provider.com" --port 23132 --hostname hostname.com --xtream-user <redacted> --xtream-password <redacted> --xtream-base-url http://<redacted>:25461 --user test123 --password test456`

When I attempt to connect using Kodi or IPTV Smarters it fails and I see the following logged to the console

`[GIN] 2019/08/31 - 21:14:17 | 404 |       2.576µs |   <ip> | GET     /player_api.php?username=test123&password=test456`

Grabbing the M3U works, however (using `hostname.com:23132/iptv.m3u?username=test123&password=456`)

Is there something I'm missing for Xtream support?

**Comment by pierre-emmanuelJ** [comment]
Thanks for this issue! It's weird, that looks good.
I'll check and then come back to you ASAP

**Comment by pierre-emmanuelJ** [comment]
It's weird I have try exactly with the same setting, and tested with iptv smarter iphone/android and I got this:

```
[GIN] 2019/09/02 - 16:00:13 | 200 |   26.753518ms |   <ip> | GET      /player_api.php?password=test456&username=test123
```

**Comment by itsneil** [comment]
Is it possible that the provider detects the proxying and blocks it? Could my 404 actually be the proxy failing to connect to the existing service, as opposed to me failing to connect to the proxy?

**Comment by pierre-emmanuelJ** [comment]
> Is it possible that the provider detects the proxying and blocks it? Could my 404 actually be the proxy failing to connect to the existing service, as opposed to me failing to connect to the proxy?
> […](#)
> On 2 Sep 2019, at 17:06, Pierre-Emmanuel Jacquier ***@***.***> wrote: ﻿ It's weird I have try exactly with the same setting, and tested with iptv smarter iphone/android and I got this: [GIN] 2019/09/02 - 16:00:13 | 200 | 26.753518ms | <ip> | GET /player_api.php?password=test456&username=test123 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

Do you think the user-agent is inportant for your provider?

**Comment by pierre-emmanuelJ** [comment]
Your provider is compatible with the latest version of iptv smarter using xtream login?

**Comment by itsneil** [comment]
Yes, as I use IPTV Smarters normally (downloaded from store, put details in, works)

User Agent I’m not sure, I will ask but they are not keen on people using it in other ways...

I’m wondering if the proxy is unable to contact my provider, and that’s 404-OMG

**Comment by pierre-emmanuelJ** [comment]
> Yes, as I use IPTV Smarters normally (downloaded from store, put details in, works) User Agent I’m not sure, I will ask but they are not keen on people using it in other ways... I’m wondering if the proxy is unable to contact my provider, and that’s 404-OMG
> […](#)
> On 2 Sep 2019, at 17:17, Pierre-Emmanuel Jacquier ***@***.***> wrote: ﻿ Your provider is compatible with the latest version of iptv smarter using xtream login? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

I always return the status code from the provider, I never reply with a 404, excepted with GIN if you  request the wrong endpoint

**Comment by pierre-emmanuelJ** [comment]
Did you solve your problem @itsneil ?

**Comment by itsneil** [comment]
I did! It mirrored my username and password in the —user and —password fields and it seemed to behave. Thank you for replying!

**Comment by pierre-emmanuelJ** [comment]
It's weird! I never seen that problem (I have tried couple of different xtream provider)

**Comment by itsneil** [comment]
I wouldn’t put it past my provider to be difficult…

**Comment by pierre-emmanuelJ** [comment]
Send me an email if you want to speak about your provider :wink:
