### ISSUE TITLE
request - Generate M3U from xtream-codes API without original M3U

### ISSUE THREAD

**Issue by dietcoke73** [pierre-emmanuelJ/iptv-proxy#94]
Many providers are now blocking M3U download, in favour of just offering the xtream-codes API.  Can iptv-proxy generate an M3U from the xtream-code API without having an M3U from the upstream portal.  I have been unable to get this to work.

**Comment by pierre-emmanuelJ** [comment]
Thanks, for your issue, I will add a flag to do it since We want to keep backward compatibility with the get.php endpoint.

**Comment by starwarskidfan** [comment]
Also curious about this.

**Comment by pierre-emmanuelJ** [comment]
A pull request has been opened to add this feature

**Comment by madasus** [comment]
It looks like this might have been added - are there any instructions on how to use?

**Comment by pierre-emmanuelJ** [comment]
Here are some instructions in the description:
https://github.com/pierre-emmanuelJ/iptv-proxy/pull/104#issue-1092605051

Need to add it to readme

**Comment by wilsoniain** [comment]
Just to confirm, where is the /apiget endpoint to be used? An example would be really great.

**Comment by edrock200** [comment]
> Just to confirm, where is the /apiget endpoint to be used? An example would be really great.

After playing with this for a while, in your docker or command line, basically don't include the m3u-url value, and add env variable XTREAM_API_GET=1 - So for example if running on the local linux host you would do
`export XTREAM_API_GET=1
iptv-proxy --port 8080 \
             --hostname proxy \
             --xtream-user iptv_account_username \
             --xtream-password iptv_account_password \
             --xtream-base-url http://iptv_provider_url:123 \
             --user proxied_username \
             --password proxied_password`

Lets say you run this on host with ip 1.1.1.1 - in your iptv app, you'd put in http://1.1.1.1:8080/get.php?username=proxied_username&password=proxied_password&type=m3u_plus&output=m3u8   (or change output to =ts if desired)

Hope this helps someone else out there. Took me a few to figure it out.

**Comment by hodgsonio** [comment]
Can I confirm the 'export XTREAM_API_GET=1' should just be another ENV value (I use Docker on Synology which is GUI based). So...

iptv-proxy --port 8080 \
             --hostname proxy \
             --xtream-user iptv_account_username \
             --xtream-password iptv_account_password \
             --xtream-base-url http://iptv_provider_url:123 \
             --user proxied_username \
             --password proxied_password
             -- XTREAM_API_GET 1

**Comment by edrock200** [comment]
Correct
