### ISSUE TITLE
Some video making apps crash

### ISSUE THREAD

**Issue by Tekka90** [pierre-emmanuelJ/iptv-proxy#95]
Hi Pierre Emmanuel,
I freshly discovered your project and am trying to use it in a docker container.
It globally works great! All my stream live are working fine in all apps (appart from iplayTV, but I guess this is the fault of the app as all other are working fine)

However what make me create an issue is a weird behavior.
For some videos, when I try to start playing though iptv-proxy, the App I use are crashing... Here is what I tried until now:
- Play like describe the specific video (this is not the case for all of them !) with IPTV Smarters pro on AppleTV -> crash (of the client, not the iptv-proxy...)
- Play like describe the specific video Lilly player on AppleTV -> crash
- Play like describe the specific video with IPTV Smarters pro on iPad Pro -> crash
- Play the exact same video in IPTV Smarters pro on iPad Pro, but without the proxy -> no issue !

I would like to deep dive more and give more input, but my issue is that I don't see anything in the logs ! Last call I get is "get-serie-info" because the video in question is an episode of a série and the system get the details. Which works, with no issue, and then I have no trace of any further request...
Could you please tell me if there is a way to make the logs more verbose to start with ? I set GIN to debug, and I get more logs, but still the same at the breaking point :(

FYI, I m using for now the docker version already built "pierro777/iptv-proxy"
I'm no go developper, but I can definitely do some debugging to help tackle this weird issue...
I will now try to get more details about this specific video versus another one which is working fine...

Regards,
Stephane

**Comment by pierre-emmanuelJ** [comment]
Hello, as I mentioned in this issue: https://github.com/pierre-emmanuelJ/iptv-proxy/issues/96#issuecomment-921068321
`docker ps` get the container ID, `docker logs -f <container-id>` then you can show me the logs.

For the issue when getting some movies or stream info could be rated to the app, failing parsing the API fields types.
Some issue is already related to that in the project: https://github.com/pierre-emmanuelJ/iptv-proxy/issues/89

Working on it when I have time, maybe could solve this issue.

Thanks
